### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by randeep01** [randeep01/algo#1]
- [ ] Find the number of occurrences of a number in array recursive approach. 
- [ ] inorder predecessor and successor 
- [ ] Reverse linked list using recursion 
-[] insertion sort with n elements sorted
